services:
  libretranslate:
    build:
      context: .
      dockerfile: docker/libretranslate/docker/Dockerfile
    ports:
      - "0.0.0.0:5000:5000"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: tradutor_legendas
      POSTGRES_USER: tradutor_legendas
      POSTGRES_PASSWORD: tradutor_legendas
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

